/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
}

type ActionName = 'CubeAction'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes } = useGLTF('/cube.glb') as unknown as GLTFResult
  // const { actions } = useAnimations<GLTFActions>(animations, group)
  useFrame(
    ({ clock }) =>
      group.current && (group.current.rotation.y = clock.getElapsedTime())
  )
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          rotation={[0, 0, 0]}
          scale={[1.5, 1.5, 1.5]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/cube.glb')
